version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: online_purchase_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    container_name: nestjs
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  ui:
    container_name: nextjs
    build: ./ui
    ports:
      - "3001:3000"

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - mysql
    environment:
      LIQUIBASE_URL: jdbc:mysql://mysql:3306/online_purchase_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      LIQUIBASE_USERNAME: user
      LIQUIBASE_PASSWORD: password
      LIQUIBASE_DRIVER: com.mysql.cj.jdbc.Driver
    command:
      [
        "--url=jdbc:mysql://mysql:3306/online_purchase_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true",
        "--driver=com.mysql.cj.jdbc.Driver",
        "--changeLogFile=changelog/db.changelog-master.xml",
        "--username=user",
        "--password=password",
        "update"
      ]
    volumes:
      - ./db/changelog:/liquibase/changelog

volumes:
  mysql-data:
